version: '3'
services:
  meu_container_php:
    build:
      context: ./docker
    volumes:
      - ./public:/var/www/html
    ports:
      - 8080:80
    networks:
      - minha_rede


networks:
  minha_rede:
    driver: bridge

